[package]
name = "lofi_rust"
version = "0.1.0"
authors = ["afentev"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sfml = "*"
vlc-rs = "*"
